### ISSUE TITLE
documentation question

### ISSUE THREAD

**Issue by zbeekman** [arporter/habakkuk#2]
Hi,

Which Fortran dialects are supported? Can this handle F2008 object oriented style code?

**Comment by arporter** [comment]
Hi Izaak,

In theory, F2003 and backwards. In practice the Fortran parser from f2py is
a bit buggy (e.g. I discovered the other day that it only recognised
PRIVATE if it was uppercase!). I'm working to improve it as I go along.

Note also that I've been naughty and broken trunk/master (because I assumed
only I was looking at it). Hopefully I'll get it fixed today.

God bless,

Andy.
